version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    hostname: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener
    ports:
      - 5432:5432

